# Generated by Django 5.1.2 on 2024-10-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyratehistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
