# Generated by Django 5.1.2 on 2024-10-18 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currencyratehistory_date'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionuser',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
    ]
